name: digital_time_capsule
description: "A time capsule with a message for the future."

publish_to: 'none'

version: 1.0.0+3
environment:
  sdk: ^3.10.4

dependencies:
  intl: ^0.19.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"  
  adaptive_icon_foreground: "assets/logo/logo.png"
